mysql:
  container_name: test-mysql-5.6.23
  build: docker
  restart: always
  ports:
    - "33060:3306"
  environment:
       TZ : "Asia/Shanghai"
       MYSQL_ROOT_PASSWORD: 123456
       MYSQL_DATABASE: product
  command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci